# Generated by Django 2.0.6 on 2018-09-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Zcareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=22)),
                ('title', models.CharField(max_length=22)),
                ('salary', models.CharField(max_length=22)),
                ('company', models.CharField(max_length=33)),
                ('job', models.TextField()),
                ('uptime', models.CharField(max_length=33)),
                ('exper', models.CharField(max_length=33)),
                ('edu', models.CharField(max_length=33)),
                ('loc', models.CharField(max_length=44)),
                ('brief_company', models.TextField()),
                ('host', models.CharField(max_length=22)),
                ('times', models.CharField(max_length=33)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 't_zhilian',
            },
        ),
    ]
